---
 - name: Print the verbosity level
   hosts: local
   tasks:
    - name: Print the first message
      debug:
        msg: "This is default message"
    - name: verbosity is 2
      debug:
        msg: "Verbosity is 2"
        verbosity: 2   