---
- name: Install tomcat9
  hosts: appserver
  become: yes
  vars:
    Java_version:  openjdk-11-jdk
    tomcat_user: tomcat
    tomcat_user_directory:  /opt/tomcat
    tomcat_user_shell:  /bin/false
    tomcat_version: '9.0.54'
  tasks:
  - name: Install java and update package
    apt:
      name: "{{ Java_version }}"
      state: present
      update_cache: yes
  - name: add tomcat user
    ansible.builtin.user:
      name: "{{ tomcat_user }}"
      home: "{{ tomcat_user_directory }}"
      shell: "{{ tomcat_user_shell }}"
      state: present
  - name: download tomcat distribution
    get_url:
      url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
      dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
  - name: untar the tomcat package
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
      dest: "{{ tomcat_user_directory }}"
  - name: create a symlink
    ansible.builtin.file:
      src: "{{ tomcat_user_directory }}/apache-tomcat-{{ tomcat_version }}"
      dest: "{{ tomcat_user_directory }}/latest"
      state: link
  - name: give ownership to tomcat user and group
    ansible.builtin.file:
      path: "{{ tomcat_user_directory }}"
      state: directory
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_user }}"
      recurse: yes
  - name: find all the shell files in the binaries
    find:
      path: "{{ tomcat_user_directory }}/latest/bin/"
      patterns: "*.sh"
    register: shfiles
  - name: print the values
    debug:
      var: shfiles
  - set_fact: 
      tomcat_executables: "{{ shfiles.files | map(attribute='path') | list }}"
  - name: print the values
    debug:
      var: tomcat_executables
  - name: change permission of shell files
    file:
      name: "{{ item }}" 
      mode: 0751
    with_items: "{{ tomcat_executables }}"