# Conditional Statement
# when : It condition is similar to the If condition in other programming language.
# failed_when
# changed_when


---
- name: Working with when conditional statement
  hosts: localhost
  gather_facts: false
  vars:
    x: 5
    y: 64
    list: [5,6,7]
  tasks:
    - name: compare the x equal to y
      debug:
        msg: "The value of x is {{x}} and value of y is {{y}}"
      when: x == y
    - name: x in list
      debug:
        msg: "x = {{x}} is present in list {{list}}data type"
      when: x in list   