---
- hosts: localhost
  gathers_facts: false
  tasks:
    - name: Finding files in /home
      command: "ls /home"
      register: home_out
    rescue:
      - debug:
          msg: "The given path: /home/ansadmin/tomcat8 is not a validpath"
    always:
      - debug:
          msg: "THis will always executes"