---
- name: install webserver with php
  hosts: webserver
  become: yes
  tasks:
  - name: fail on unsupported version
    fail:
      msg: This playbook supports only centos 7 and ubuntu 20 distribution
    when:
      - ansible_facts['distribution'] != "Ubuntu"
      - ansible_facts['distribution'] != "CentOS" 
      - (ansible_facts['distribution'] == "Ubuntu" and  ansible_facts['distribution_major_version'] != "20") 
      - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] != "7")
  - name: information about node and the variables loaded
    debug:
      msg: "Node OS is {{ ansible_facts['distribution'] }} package name is {{ package }} and the info location is {{ info_location }} and the php package are {{ php_packages }}"
  - name: install apache
    package:
      name: "{{ package }}"
      state: present
  - name: install php module
    package:
      name: "{{php_packages}}"
      state: present
  - name: create info.php file
    copy:
      dest: "{{ info_location }}"
      content: |
        <?php 
        phpinfo(); 
        ?>
    notify:
      - Restart apache
  handlers:
  - name: Restart apache
    service:
      name: "{{ package }}"
      state: restarted
      enabled: yes 
    