---
- name: install webserver
  hosts: localhost
  become: yes
  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present
      update_cache: yes 
  - name: Install php modules
    apt:
      name:
        - php
        - libapache2-mod-php
        - php-mysql
      state: present
  - name: create info.php file
    copy:
      dest: /var/www/html/info.php
      content: | 
        <?php
        phpinfo();
        ?>
